// Save + list PP item quotes. Admin-only (no client side for PP).
// Mirrors /api/calc/box-quotes and /api/calc/cup-quotes.
//
// Airtable table "PP Quotes" (override via AIRTABLE_PP_QUOTES_TABLE) — fields:
//   • Quote Ref (single line text)
//   • Quote Date (date)
//   • Item Name (single line text)
//   • Preset Key (single line text)
//   • Item Weight g (number)
//   • Cavities (number)            — items-per-shot
//   • Cycle Time s (number)
//   • Shift Hrs (number)
//   • Shifts per Day (number)
//   • Labour Cost per Day INR (number)
//   • RM Rate INR (number)
//   • Runner g per Shot (number)
//   • Regrind % (number)
//   • Machine Power kW (number)
//   • Electricity Rate (number)
//   • Mold Cost INR (number)
//   • Mold Life Shots (number)
//   • Reject % (number)
//   • Inner Sleeve Cost INR (number)
//   • Inner Packing Labour INR (number)
//   • Units per Sleeve (number)
//   • Carton Cost INR (number)
//   • Case Pack (number)
//   • Profit % (number)
//   • Mfg Cost INR (number)
//   • Selling Price INR (number)
//   • SP per Case INR (number)
//   • Generated By (single line text)
//   • Notes (long text)

import { airtableList, airtableCreate, airtableUpdate, TABLES } from "@/lib/calc/airtable";
import { getSession } from "@/lib/calc/session";

export const runtime = "nodejs";

function recordToQuote(r) {
  const f = r.fields || {};
  return {
    id: r.id,
    quoteRef: f["Quote Ref"] || "",
    date: f["Quote Date"] || "",
    itemName: f["Item Name"] || "",
    presetKey: f["Preset Key"] || "",
    itemWeight: f["Item Weight g"] ?? null,
    cavities: f.Cavities ?? null,
    cycleTime: f["Cycle Time s"] ?? null,
    shiftHrs: f["Shift Hrs"] ?? null,
    shiftsPerDay: f["Shifts per Day"] ?? null,
    labourCostPerDay: f["Labour Cost per Day INR"] ?? null,
    rmRate: f["RM Rate INR"] ?? null,
    runnerWeightPerShot: f["Runner g per Shot"] ?? null,
    regrindCapturePercent: f["Regrind %"] ?? null,
    machinePowerKw: f["Machine Power kW"] ?? null,
    electricityRate: f["Electricity Rate"] ?? null,
    moldCost: f["Mold Cost INR"] ?? null,
    moldLifeShots: f["Mold Life Shots"] ?? null,
    rejectPercent: f["Reject %"] ?? null,
    innerSleeveCost: f["Inner Sleeve Cost INR"] ?? null,
    innerPackingLabour: f["Inner Packing Labour INR"] ?? null,
    unitsPerSleeve: f["Units per Sleeve"] ?? null,
    cartonCost: f["Carton Cost INR"] ?? null,
    casePack: f["Case Pack"] ?? null,
    profitPct: f["Profit %"] ?? null,
    mfgCost: f["Mfg Cost INR"] ?? null,
    sellingPrice: f["Selling Price INR"] ?? null,
    spPerCase: f["SP per Case INR"] ?? null,
    generatedBy: f["Generated By"] || "",
    notes: f.Notes || "",
  };
}

function payloadToFields(body) {
  const fields = {
    "Quote Ref": body.quoteRef || undefined,
    "Item Name": body.itemName || undefined,
    "Preset Key": body.presetKey || undefined,
    "Item Weight g": body.itemWeight !== undefined ? Number(body.itemWeight) : undefined,
    Cavities: body.cavities !== undefined ? Number(body.cavities) : undefined,
    "Cycle Time s": body.cycleTime !== undefined ? Number(body.cycleTime) : undefined,
    "Shift Hrs": body.shiftHrs !== undefined ? Number(body.shiftHrs) : undefined,
    "Shifts per Day": body.shiftsPerDay !== undefined ? Number(body.shiftsPerDay) : undefined,
    "Labour Cost per Day INR": body.labourCostPerDay !== undefined ? Number(body.labourCostPerDay) : undefined,
    "RM Rate INR": body.rmRate !== undefined ? Number(body.rmRate) : undefined,
    "Runner g per Shot": body.runnerWeightPerShot !== undefined ? Number(body.runnerWeightPerShot) : undefined,
    "Regrind %": body.regrindCapturePercent !== undefined ? Number(body.regrindCapturePercent) : undefined,
    "Machine Power kW": body.machinePowerKw !== undefined ? Number(body.machinePowerKw) : undefined,
    "Electricity Rate": body.electricityRate !== undefined ? Number(body.electricityRate) : undefined,
    "Mold Cost INR": body.moldCost !== undefined ? Number(body.moldCost) : undefined,
    "Mold Life Shots": body.moldLifeShots !== undefined ? Number(body.moldLifeShots) : undefined,
    "Reject %": body.rejectPercent !== undefined ? Number(body.rejectPercent) : undefined,
    "Inner Sleeve Cost INR": body.innerSleeveCost !== undefined ? Number(body.innerSleeveCost) : undefined,
    "Inner Packing Labour INR": body.innerPackingLabour !== undefined ? Number(body.innerPackingLabour) : undefined,
    "Units per Sleeve": body.unitsPerSleeve !== undefined ? Number(body.unitsPerSleeve) : undefined,
    "Carton Cost INR": body.cartonCost !== undefined ? Number(body.cartonCost) : undefined,
    "Case Pack": body.casePack !== undefined ? Number(body.casePack) : undefined,
    "Profit %": body.profitPct !== undefined ? Number(body.profitPct) : undefined,
    "Mfg Cost INR": body.mfgCost !== undefined ? Number(body.mfgCost) : undefined,
    "Selling Price INR": body.sellingPrice !== undefined ? Number(body.sellingPrice) : undefined,
    "SP per Case INR": body.spPerCase !== undefined ? Number(body.spPerCase) : undefined,
    Notes: body.notes !== undefined ? (body.notes || "") : undefined,
  };
  Object.keys(fields).forEach((k) => fields[k] === undefined && delete fields[k]);
  return fields;
}

export async function GET() {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });
  if (session.role !== "admin") return new Response("Forbidden", { status: 403 });

  const records = await airtableList(TABLES.ppQuotes(), {
    sort: [{ field: "Quote Date", direction: "desc" }],
  });
  return Response.json(records.map(recordToQuote));
}

export async function POST(req) {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });
  if (session.role !== "admin") return new Response("Forbidden", { status: 403 });
  const body = await req.json();
  const today = new Date().toISOString().split("T")[0];

  const fields = {
    ...payloadToFields(body),
    "Quote Ref": body.quoteRef || `PP ${today}`,
    "Quote Date": today,
    "Generated By": "Admin",
  };

  const created = await airtableCreate(TABLES.ppQuotes(), fields);
  return Response.json(recordToQuote(created));
}

// Update an existing PP quote. Admin-only.
export async function PATCH(req) {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });
  if (session.role !== "admin") return new Response("Forbidden", { status: 403 });
  const body = await req.json();
  if (!body.id) return Response.json({ error: "id required" }, { status: 400 });

  const fields = payloadToFields(body);
  const updated = await airtableUpdate(TABLES.ppQuotes(), body.id, fields);
  return Response.json(recordToQuote(updated));
}
