import { getSession } from "@/lib/calc/session";
import { redirect } from "next/navigation";
import { NavBar } from "@/app/calculator/_components/NavBar";
import QuoteHistoryTable from "@/app/calculator/_components/QuoteHistoryTable";

export default function AdminHistoryPage() {
  const session = getSession();
  if (!session) redirect("/calculator/login");
  if (session.role !== "admin") redirect("/calculator/client");
  return (
    <div className="min-h-screen bg-gray-50">
      <NavBar role="admin" />
      <div className="max-w-6xl mx-auto px-4 pb-10">
        <h1 className="text-2xl font-bold text-gray-900 mb-1">Quote History</h1>
        <p className="text-sm text-gray-500 mb-6">All quotes generated by admin and clients.</p>
        <QuoteHistoryTable showClientColumn />
      </div>
    </div>
  );
}
