import { airtableList, airtableCreate, escapeFormula, TABLES } from "@/lib/calc/airtable";
import { getSession } from "@/lib/calc/session";

export const runtime = "nodejs";

const BAG_TYPE_OUT = {
  sos: "SOS",
  rope_handle: "Rope Handle",
  flat_handle: "Flat Handle",
  v_bottom_gusset: "V-Bottom",
};

function recordToQuote(r) {
  const f = r.fields || {};
  return {
    id: r.id,
    quoteRef: f["Quote Ref"] || "",
    date: f["Quote Date"] || "",
    bagCode: Array.isArray(f["Bag Code"]) && f["Bag Code"].length ? f["Bag Code"][0] : null,
    brand: f.Brand || "",
    item: f.Item || "",
    bagType: f["Bag Type"] || "",
    plainPrinted: f["Plain/Printed"] || "",
    paperType: f["Paper Type"] || "",
    mill: f.Mill || "",
    gsm: f.GSM ?? null,
    bf: f.BF ?? null,
    width: f["Width mm"] ?? null,
    gusset: f["Gusset mm"] ?? null,
    height: f["Height mm"] ?? null,
    paperRate: f["Paper Rate"] ?? null,
    casePack: f["Case Pack"] ?? null,
    orderQty: f["Order Qty"] ?? null,
    wastagePct: f["Wastage %"] ?? null,
    profitPct: f["Profit %"] ?? null,
    mfgCost: f["Mfg Cost INR"] ?? null,
    sellingPrice: f["Selling Price INR"] ?? null,
    costPerCase: f["Cost per Case INR"] ?? null,
    orderTotal: f["Order Total INR"] ?? null,
    colours: f.Colours ?? null,
    coveragePct: f["Coverage %"] ?? null,
    handleCost: f["Handle Cost"] ?? null,
    clientEmail: f["Client Email"] || "",
    generatedBy: f["Generated By"] || "",
    notes: f.Notes || "",
  };
}

export async function GET() {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });

  const opts = { sort: [{ field: "Quote Date", direction: "desc" }] };
  if (session.role === "client") {
    opts.filterByFormula = `LOWER({Client Email})='${escapeFormula(session.email)}'`;
  }
  const records = await airtableList(TABLES.quotes(), opts);
  return Response.json(records.map(recordToQuote));
}

export async function POST(req) {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });
  const body = await req.json();
  const today = new Date().toISOString().split("T")[0];

  const fields = {
    "Quote Ref": body.quoteRef || `Auto ${today}`,
    "Quote Date": today,
    Brand: body.brand || undefined,
    Item: body.item || undefined,
    "Bag Type": BAG_TYPE_OUT[body.bagType] || undefined,
    "Plain/Printed": body.printing ? "Printed" : "Plain",
    "Paper Type": body.paperType || undefined,
    Mill: body.mill || undefined,
    GSM: body.gsm ? Number(body.gsm) : undefined,
    BF: body.bf ? Number(body.bf) : undefined,
    "Width mm": Number(body.width) || undefined,
    "Gusset mm": Number(body.gusset) || undefined,
    "Height mm": Number(body.height) || undefined,
    "Paper Rate": body.paperRate ? Number(body.paperRate) : undefined,
    "Case Pack": body.casePack ? Number(body.casePack) : undefined,
    "Order Qty": body.orderQty ? Number(body.orderQty) : undefined,
    "Wastage %": body.wastagePct !== undefined ? Number(body.wastagePct) : undefined,
    "Profit %": body.profitPct !== undefined ? Number(body.profitPct) : undefined,
    "Mfg Cost INR": body.mfgCost !== undefined ? Number(body.mfgCost) : undefined,
    "Selling Price INR": body.sellingPrice !== undefined ? Number(body.sellingPrice) : undefined,
    "Cost per Case INR": body.costPerCase !== undefined ? Number(body.costPerCase) : undefined,
    "Order Total INR": body.orderTotal !== undefined ? Number(body.orderTotal) : undefined,
    Colours: body.colours ? Number(body.colours) : undefined,
    "Coverage %": body.coverage ? Number(body.coverage) : undefined,
    "Handle Cost": body.handleCost ? Number(body.handleCost) : undefined,
    "Generated By": session.role === "admin" ? "Admin" : "Client",
    "Client Email": session.role === "client" ? session.email : (body.clientEmail || undefined),
    Notes: body.notes || undefined,
  };
  if (body.bagCodeId) fields["Bag Code"] = [body.bagCodeId];
  Object.keys(fields).forEach((k) => fields[k] === undefined && delete fields[k]);

  const created = await airtableCreate(TABLES.quotes(), fields);
  return Response.json(recordToQuote(created));
}
