// Save + list box quotes. Mirrors /api/calc/quotes but writes to the Box Quotes
// table (see lib/calc/airtable.js TABLES.boxQuotes()).
import { airtableList, airtableCreate, escapeFormula, TABLES } from "@/lib/calc/airtable";
import { getSession } from "@/lib/calc/session";
import { BOX_TYPE_LABEL } from "@/lib/calc/box-calculator";

export const runtime = "nodejs";

function recordToQuote(r) {
  const f = r.fields || {};
  return {
    id: r.id,
    quoteRef: f["Quote Ref"] || "",
    date: f["Quote Date"] || "",
    boxType: f["Box Type"] || "",
    plainPrinted: f["Plain/Printed"] || "",
    paperName: f["Paper"] || "",
    gsm: f.GSM ?? null,
    openLength: f["Open Length mm"] ?? null,
    openWidth: f["Open Width mm"] ?? null,
    paperRate: f["Paper Rate"] ?? null,
    qty: f["Order Qty"] ?? null,
    wastagePct: f["Wastage %"] ?? null,
    profitPct: f["Profit %"] ?? null,
    mfgCost: f["Mfg Cost INR"] ?? null,
    sellingPrice: f["Selling Price INR"] ?? null,
    orderTotal: f["Order Total INR"] ?? null,
    colours: f.Colours ?? null,
    coveragePct: f["Coverage %"] ?? null,
    punching: !!f.Punching,
    clientEmail: f["Client Email"] || "",
    generatedBy: f["Generated By"] || "",
    notes: f.Notes || "",
  };
}

export async function GET() {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });

  const opts = { sort: [{ field: "Quote Date", direction: "desc" }] };
  if (session.role === "client") {
    opts.filterByFormula = `LOWER({Client Email})='${escapeFormula(session.email)}'`;
  }
  const records = await airtableList(TABLES.boxQuotes(), opts);
  return Response.json(records.map(recordToQuote));
}

export async function POST(req) {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });
  const body = await req.json();
  const today = new Date().toISOString().split("T")[0];

  const fields = {
    "Quote Ref": body.quoteRef || `Auto ${today}`,
    "Quote Date": today,
    "Box Type": BOX_TYPE_LABEL[body.boxType] || body.boxType || undefined,
    "Plain/Printed": body.printing ? "Printed" : "Plain",
    Paper: body.paperName || undefined,
    GSM: body.gsm ? Number(body.gsm) : undefined,
    "Open Length mm": Number(body.openLength) || undefined,
    "Open Width mm": Number(body.openWidth) || undefined,
    "Paper Rate": body.paperRate ? Number(body.paperRate) : undefined,
    "Order Qty": body.qty ? Number(body.qty) : undefined,
    "Wastage %": body.wastagePct !== undefined ? Number(body.wastagePct) : undefined,
    "Profit %": body.profitPct !== undefined ? Number(body.profitPct) : undefined,
    "Mfg Cost INR": body.mfgCost !== undefined ? Number(body.mfgCost) : undefined,
    "Selling Price INR": body.sellingPrice !== undefined ? Number(body.sellingPrice) : undefined,
    "Order Total INR": body.orderTotal !== undefined ? Number(body.orderTotal) : undefined,
    Colours: body.colours ? Number(body.colours) : undefined,
    "Coverage %": body.coverage ? Number(body.coverage) : undefined,
    Punching: !!body.punching,
    "Generated By": session.role === "admin" ? "Admin" : "Client",
    "Client Email": session.role === "client" ? session.email : (body.clientEmail || undefined),
    Notes: body.notes || undefined,
  };
  Object.keys(fields).forEach((k) => fields[k] === undefined && delete fields[k]);

  const created = await airtableCreate(TABLES.boxQuotes(), fields);
  return Response.json(recordToQuote(created));
}
