// Save + list cup quotes. Mirrors /api/calc/quotes but writes to the Cup
// Quotes table (see lib/calc/airtable.js TABLES.cupQuotes()).
import { airtableList, airtableCreate, escapeFormula, TABLES } from "@/lib/calc/airtable";
import { getSession } from "@/lib/calc/session";

export const runtime = "nodejs";

function recordToQuote(r) {
  const f = r.fields || {};
  return {
    id: r.id,
    quoteRef: f["Quote Ref"] || "",
    date: f["Quote Date"] || "",
    wallType: f["Wall Type"] || "",
    size: f.Size || "",
    sku: f.SKU || "",
    innerGsm: f["Inner GSM"] ?? null,
    outerGsm: f["Outer GSM"] ?? null,
    innerCoating: f["Inner Coating"] || "",
    plainPrinted: f["Plain/Printed"] || "",
    colours: f.Colours ?? null,
    coveragePct: f["Coverage %"] ?? null,
    casePack: f["Case Pack"] ?? null,
    orderQty: f["Order Qty"] ?? null,
    marginPct: f["Margin %"] ?? null,
    mfgCost: f["Mfg Cost INR"] ?? null,
    sellingPrice: f["Selling Price INR"] ?? null,
    costPerCase: f["Cost per Case INR"] ?? null,
    orderTotal: f["Order Total INR"] ?? null,
    cupWeightG: f["Cup Weight g"] ?? null,
    oneTimeTotal: f["One-time Plate/Die INR"] ?? null,
    clientEmail: f["Client Email"] || "",
    generatedBy: f["Generated By"] || "",
    notes: f.Notes || "",
  };
}

export async function GET() {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });

  const opts = { sort: [{ field: "Quote Date", direction: "desc" }] };
  if (session.role === "client") {
    opts.filterByFormula = `LOWER({Client Email})='${escapeFormula(session.email)}'`;
  }
  try {
    const records = await airtableList(TABLES.cupQuotes(), opts);
    return Response.json(records.map(recordToQuote));
  } catch (e) {
    // Table may not exist yet in Airtable — return empty list rather than 500.
    console.error("Cup quotes list failed:", e?.message || e);
    return Response.json([]);
  }
}

export async function POST(req) {
  const session = getSession();
  if (!session) return new Response("Unauthorized", { status: 401 });
  const body = await req.json();
  const today = new Date().toISOString().split("T")[0];

  const fields = {
    "Quote Ref": body.quoteRef || `Cup ${today}`,
    "Quote Date": today,
    "Wall Type": body.wallType || undefined,
    Size: body.size || undefined,
    SKU: body.sku || undefined,
    "Inner GSM": body.innerGsm ? Number(body.innerGsm) : undefined,
    "Outer GSM": body.outerGsm ? Number(body.outerGsm) : undefined,
    "Inner Coating": body.innerCoating || undefined,
    "Plain/Printed": body.printing ? "Printed" : "Plain",
    Colours: body.colours ? Number(body.colours) : undefined,
    "Coverage %": body.coverage ? Number(body.coverage) : undefined,
    "Case Pack": body.casePack ? Number(body.casePack) : undefined,
    "Order Qty": body.orderQty ? Number(body.orderQty) : undefined,
    "Margin %": body.marginPct !== undefined ? Number(body.marginPct) : undefined,
    "Mfg Cost INR": body.mfgCost !== undefined ? Number(body.mfgCost) : undefined,
    "Selling Price INR": body.sellingPrice !== undefined ? Number(body.sellingPrice) : undefined,
    "Cost per Case INR": body.costPerCase !== undefined ? Number(body.costPerCase) : undefined,
    "Order Total INR": body.orderTotal !== undefined ? Number(body.orderTotal) : undefined,
    "Cup Weight g": body.cupWeightG !== undefined ? Number(body.cupWeightG) : undefined,
    "One-time Plate/Die INR": body.oneTimeTotal !== undefined ? Number(body.oneTimeTotal) : undefined,
    "Generated By": session.role === "admin" ? "Admin" : "Client",
    "Client Email": session.role === "client" ? session.email : (body.clientEmail || undefined),
    Notes: body.notes || undefined,
  };
  Object.keys(fields).forEach((k) => fields[k] === undefined && delete fields[k]);

  try {
    const created = await airtableCreate(TABLES.cupQuotes(), fields);
    return Response.json(recordToQuote(created));
  } catch (e) {
    console.error("Cup quote save failed:", e?.message || e);
    return Response.json(
      { error: "Save failed — check that a 'Cup Quotes' table exists in Airtable with the expected field names." },
      { status: 500 }
    );
  }
}
