// Save + list Import Calculator quotes (China → India). Internal-only —
// any FactoryOS internal role can read/write. Mirrors /api/calc/pp-quotes
// in shape but adds an items_json field for the variable line items.

import { airtableList, airtableCreate, airtableUpdate, TABLES } from "@/lib/calc/airtable";
import { getSession as getCalcSession } from "@/lib/calc/session";
import { getSession as getFactoryosSession } from "@/lib/factoryos/session";
import { isInternalRole } from "@/lib/factoryos/constants";

export const runtime = "nodejs";

function gate() {
  if (!getCalcSession()) return new Response("Unauthorized", { status: 401 });
  const fos = getFactoryosSession();
  if (!fos || !isInternalRole(fos.role)) {
    return new Response("Forbidden", { status: 403 });
  }
  return null;
}

function recordToQuote(r) {
  const f = r.fields || {};
  return {
    id: r.id,
    createdAt: r.createdTime,
    quoteRef: f["Quote Ref"] || "",
    date: f["Quote Date"] || "",
    vendorId: f["Vendor Id"] || "",
    vendorName: f["Vendor Name"] || "",
    shipmentType: f["Shipment Type"] || "",
    fobCurrency: f["FOB Currency"] || "",
    fxRate: f["FX Rate"] ?? null,
    freightCurrency: f["Freight Currency"] || "",
    dutyPct: f["Duty Pct"] ?? null,
    marginPct: f["Margin Pct"] ?? null,
    outputGstPct: f["Output GST Pct"] ?? null,
    freightAmount: f["Freight Amount"] ?? null,
    freightMode: f["Freight Mode"] || "",
    inlandAmount: f["Inland Amount"] ?? null,
    inlandMode: f["Inland Mode"] || "",
    unofficialAmount: f["Unofficial Amount"] ?? null,
    unofficialMode: f["Unofficial Mode"] || "",
    handlingAmount: f["Handling Amount"] ?? null,
    handlingMode: f["Handling Mode"] || "",
    lclRate: f["LCL Rate"] ?? null,
    lclCbm: f["LCL CBM"] ?? null,
    items: Array.isArray(f["Items JSON"]) ? f["Items JSON"] : [],
    itemsCount: f["Items Count"] ?? null,
    totalLandedINR: f["Total Landed INR"] ?? null,
    totalFinalSellingINR: f["Total Final Selling INR"] ?? null,
    generatedBy: f["Generated By"] || "",
    notes: f.Notes || "",
  };
}

function payloadToFields(body) {
  const fields = {
    "Quote Ref": body.quoteRef !== undefined ? body.quoteRef : undefined,
    "Vendor Id": body.vendorId !== undefined ? body.vendorId : undefined,
    "Vendor Name": body.vendorName !== undefined ? body.vendorName : undefined,
    "Shipment Type": body.shipmentType !== undefined ? body.shipmentType : undefined,
    "FOB Currency": body.fobCurrency !== undefined ? body.fobCurrency : undefined,
    "FX Rate": body.fxRate !== undefined ? Number(body.fxRate) : undefined,
    "Freight Currency": body.freightCurrency !== undefined ? body.freightCurrency : undefined,
    "Duty Pct": body.dutyPct !== undefined ? Number(body.dutyPct) : undefined,
    "Margin Pct": body.marginPct !== undefined ? Number(body.marginPct) : undefined,
    "Output GST Pct": body.outputGstPct !== undefined ? Number(body.outputGstPct) : undefined,
    "Freight Amount": body.freightAmount !== undefined ? Number(body.freightAmount) : undefined,
    "Freight Mode": body.freightMode !== undefined ? body.freightMode : undefined,
    "Inland Amount": body.inlandAmount !== undefined ? Number(body.inlandAmount) : undefined,
    "Inland Mode": body.inlandMode !== undefined ? body.inlandMode : undefined,
    "Unofficial Amount": body.unofficialAmount !== undefined ? Number(body.unofficialAmount) : undefined,
    "Unofficial Mode": body.unofficialMode !== undefined ? body.unofficialMode : undefined,
    "Handling Amount": body.handlingAmount !== undefined ? Number(body.handlingAmount) : undefined,
    "Handling Mode": body.handlingMode !== undefined ? body.handlingMode : undefined,
    "LCL Rate": body.lclRate !== undefined ? Number(body.lclRate) : undefined,
    "LCL CBM": body.lclCbm !== undefined ? Number(body.lclCbm) : undefined,
    "Items JSON": Array.isArray(body.items) ? body.items : undefined,
    "Items Count": body.itemsCount !== undefined ? Number(body.itemsCount) : undefined,
    "Total Landed INR": body.totalLandedINR !== undefined ? Number(body.totalLandedINR) : undefined,
    "Total Final Selling INR": body.totalFinalSellingINR !== undefined ? Number(body.totalFinalSellingINR) : undefined,
    Notes: body.notes !== undefined ? (body.notes || "") : undefined,
  };
  Object.keys(fields).forEach((k) => fields[k] === undefined && delete fields[k]);
  return fields;
}

export async function GET() {
  const blocked = gate();
  if (blocked) return blocked;

  const records = await airtableList(TABLES.importQuotes(), {
    sort: [{ field: "Quote Date", direction: "desc" }],
  });
  return Response.json(records.map(recordToQuote));
}

export async function POST(req) {
  const blocked = gate();
  if (blocked) return blocked;

  const body = await req.json();
  const today = new Date().toISOString().split("T")[0];
  const fos = getFactoryosSession();

  const fields = {
    ...payloadToFields(body),
    "Quote Ref":
      body.quoteRef ||
      `IMP ${today}${body.vendorName ? ` — ${body.vendorName}` : ""}`,
    "Quote Date": today,
    "Generated By": fos?.email || "Internal",
  };

  const created = await airtableCreate(TABLES.importQuotes(), fields);
  return Response.json(recordToQuote(created));
}

export async function PATCH(req) {
  const blocked = gate();
  if (blocked) return blocked;

  const body = await req.json();
  if (!body.id) return Response.json({ error: "id required" }, { status: 400 });

  const fields = payloadToFields(body);
  const updated = await airtableUpdate(TABLES.importQuotes(), body.id, fields);
  return Response.json(recordToQuote(updated));
}
